front:
  build: .
  ports:
    - "3000:3000"
    - "3001:3001"
  links:
    - mysql:mysql
    - redis:redis
  volumes:
    - ./www/:/www/
  entrypoint: /usr/bin/supervisord

mysql:
  image: mysql
  ports:
    - "3306:3306"
  environment:
    MYSQL_DATABASE: test
    MYSQL_ROOT_PASSWORD: root

redis:
  image: redis
  ports:
    - "6379:6379"